# Generated by Django 4.1 on 2022-10-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidDeck', '0005_alter_missionary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundapply',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
